export { default as facebook } from './facebook.svg'
export { default as github } from './github.svg'
export { default as instagram } from './instagram.svg'
export { default as twitter } from './twitter.svg'
export { default as wantedly } from './wantedly.svg'
export { default as qiita } from './qiita.jpg'
